### ISSUE TITLE
TCP socket reader/writer backwards

### ISSUE THREAD

**Issue by chrismwendt** [chemzqm/wxml-languageserver#1]
I think this is backwards:

https://github.com/chemzqm/wxml-languageserver/blob/d46dbfccd6f8398ac551c9ed217626601f9f19fb/src/utils/connectionFromOptions.ts#L32-L33

It should be:

```typescript
            socket.pipe(reader)
            writer.pipe(socket)
```

**Comment by chemzqm** [comment]
You're right, although they works the same.
